// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// scollateC
std::vector<int> scollateC(std::vector<double> x, std::vector<double> boundaries);
RcppExport SEXP _sift_scollateC(SEXP xSEXP, SEXP boundariesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type x(xSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type boundaries(boundariesSEXP);
    rcpp_result_gen = Rcpp::wrap(scollateC(x, boundaries));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sift_scollateC", (DL_FUNC) &_sift_scollateC, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_sift(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
