<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Introducing conjecture • sift</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha256-bZLfwXAP04zRMK2BjiO8iu9pf4FbLqX6zitd+tIvLhE=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Introducing conjecture">
<meta property="og:description" content="sift">
<meta property="og:image" content="/logo.png">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">sift</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">0.1.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/conjecture.html">Introducing conjecture</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right"></ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="conjecture_files/accessible-code-block-0.0.1/empty-anchor.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Introducing conjecture</h1>
            
      
      
      <div class="hidden name"><code>conjecture.Rmd</code></div>

    </div>

    
    
<p><code><a href="../reference/conjecture.html">conjecture()</a></code> is the black swan of the <code>sift</code> family. If you encounter the type of eccentric datasets conjecture is designed to tackle, you’ll be glad you read this vignette.</p>
<p>At its heart, conjecture is a reshaping operation similar to <code><a href="https://tidyr.tidyverse.org/reference/pivot_wider.html">tidyr::pivot_wider()</a></code>. However, the intended application for conjecture is more idiosyncratic than that of pivot_wider. This vignette illustrates the basic aspects of such an application.</p>
<div id="example-1-radio-transmissions" class="section level2">
<h2 class="hasAnchor">
<a href="#example-1-radio-transmissions" class="anchor"></a>Example 1: Radio Transmissions</h2>
<p>The <code>comms</code> dataset contains a time-series of radio transmissions.</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va">sift</span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyr.tidyverse.org">tidyr</a></span><span class="op">)</span>

<span class="va">comms</span>
<span class="co">#&gt; # A tibble: 50,000 x 4</span>
<span class="co">#&gt;    station timestamp           msg_code type   </span>
<span class="co">#&gt;    &lt;chr&gt;   &lt;dttm&gt;                 &lt;int&gt; &lt;chr&gt;  </span>
<span class="co">#&gt;  1 D       1999-01-21 03:37:57     2537 send   </span>
<span class="co">#&gt;  2 C       1999-01-24 11:52:07      720 send   </span>
<span class="co">#&gt;  3 D       1999-01-25 03:12:31     1332 receive</span>
<span class="co">#&gt;  4 D       1999-01-25 11:46:18     2959 receive</span>
<span class="co">#&gt;  5 B       1999-01-25 13:43:17      512 receive</span>
<span class="co">#&gt;  6 A       1999-01-25 19:08:25     2197 receive</span>
<span class="co">#&gt;  7 B       1999-01-25 19:26:43      986 receive</span>
<span class="co">#&gt;  8 A       1999-01-25 23:13:40     2851 receive</span>
<span class="co">#&gt;  9 B       1999-01-26 04:04:34     2108 receive</span>
<span class="co">#&gt; 10 D       1999-01-26 11:50:58     2531 send   </span>
<span class="co">#&gt; # … with 49,990 more rows</span></code></pre></div>
<p>A few notes:</p>
<ul>
<li>We are <strong>not interested</strong> in the interaction between the stations. Each station (A, B, C, D) can be regarded as 4 independent time-series.</li>
<li>The subject of each transmission is denoted by <code>msg_code</code>.</li>
<li>Each <code>msg_code</code> can be repeated multiple times (see below).</li>
<li>There is <strong>no guarantee</strong> that a <em>sent</em> transmission will be met with a <em>response</em> sharing the same <code>msg_code</code>.</li>
</ul>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">comms</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">station</span> <span class="op">==</span> <span class="st">"C"</span>,
         <span class="va">msg_code</span> <span class="op">==</span> <span class="fl">3060</span><span class="op">)</span>
<span class="co">#&gt; # A tibble: 14 x 4</span>
<span class="co">#&gt;    station timestamp           msg_code type   </span>
<span class="co">#&gt;    &lt;chr&gt;   &lt;dttm&gt;                 &lt;int&gt; &lt;chr&gt;  </span>
<span class="co">#&gt;  1 C       1999-02-10 01:33:11     3060 send   </span>
<span class="co">#&gt;  2 C       1999-02-11 21:43:31     3060 receive</span>
<span class="co">#&gt;  3 C       1999-02-14 17:07:35     3060 send   </span>
<span class="co">#&gt;  4 C       1999-02-17 08:31:48     3060 receive</span>
<span class="co">#&gt;  5 C       1999-02-18 11:33:57     3060 receive</span>
<span class="co">#&gt;  6 C       1999-02-19 00:43:25     3060 receive</span>
<span class="co">#&gt;  7 C       1999-02-20 23:24:25     3060 send   </span>
<span class="co">#&gt;  8 C       1999-02-21 03:00:18     3060 send   </span>
<span class="co">#&gt;  9 C       1999-02-21 19:13:55     3060 send   </span>
<span class="co">#&gt; 10 C       1999-02-22 09:38:07     3060 receive</span>
<span class="co">#&gt; 11 C       1999-02-22 14:39:10     3060 send   </span>
<span class="co">#&gt; 12 C       1999-02-26 09:41:56     3060 receive</span>
<span class="co">#&gt; 13 C       1999-02-28 23:35:59     3060 receive</span>
<span class="co">#&gt; 14 C       1999-03-01 05:54:49     3060 receive</span></code></pre></div>
<p>Suppose we wish to restructure <code>comms</code> so that the “natural” pairing of <code>send</code> + <code>receive</code> transmissions is more apparent. Since there is no explicit information linking these rows together, we “conjecture” that, for a given <code>send</code> transmission (anterior), the corresponding <code>receive</code> transmission (posterior) is the closest observation measured by <code>timestamp</code>.</p>
<p><code><a href="../reference/conjecture.html">conjecture()</a></code> always takes <strong>4</strong> arguments.</p>
<ol style="list-style-type: decimal">
<li>Dataset to reshape (<code>comms</code>).</li>
<li>Column, as a symbol, used to measure distance between observations (<code>timestamp</code>).</li>
<li>Column, as a symbol, that demarks observations as anterior or posterior (<code>type</code>).</li>
<li>Scalar quantity signifying anterior observation (<code>"send"</code>).</li>
</ol>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">comms_conjecture</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/conjecture.html">conjecture</a></span><span class="op">(</span><span class="va">comms</span>,     <span class="co"># dataset to reshape.</span>
                               <span class="va">timestamp</span>, <span class="co"># &lt;dttm&gt; friendly. must be coercible to numeric.</span>
                               <span class="va">type</span>,      <span class="co"># any type of atomic vector is fine.</span>
                               <span class="st">"send"</span><span class="op">)</span>    <span class="co"># we could flip our logic and supply "receive" instead.</span>

<span class="va">comms_conjecture</span>
<span class="co">#&gt; # A tibble: 24,958 x 4</span>
<span class="co">#&gt;    station msg_code send                receive            </span>
<span class="co">#&gt;    &lt;chr&gt;      &lt;int&gt; &lt;dttm&gt;              &lt;dttm&gt;             </span>
<span class="co">#&gt;  1 D           2537 1999-01-21 03:37:57 1999-02-15 21:56:29</span>
<span class="co">#&gt;  2 C            720 1999-01-24 11:52:07 1999-02-22 12:24:57</span>
<span class="co">#&gt;  3 D           2531 1999-01-26 11:50:58 1999-02-09 07:14:33</span>
<span class="co">#&gt;  4 D           2992 1999-01-27 02:48:56 1999-02-22 12:05:55</span>
<span class="co">#&gt;  5 A           2262 1999-01-27 09:19:56 1999-02-11 19:43:42</span>
<span class="co">#&gt;  6 B           1785 1999-01-27 12:11:04 1999-02-07 03:07:50</span>
<span class="co">#&gt;  7 C           1624 1999-01-27 15:33:09 1999-02-20 05:07:54</span>
<span class="co">#&gt;  8 C           2280 1999-01-27 20:06:18 1999-02-18 11:25:13</span>
<span class="co">#&gt;  9 B           1170 1999-01-28 00:55:33 NA                 </span>
<span class="co">#&gt; 10 B           2137 1999-01-28 02:30:30 1999-02-26 17:13:21</span>
<span class="co">#&gt; # … with 24,948 more rows</span></code></pre></div>
<p>We can partially achieve the same result with pivot_wider.</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">comms_pivot</span> <span class="op">&lt;-</span> <span class="va">comms</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_wider.html">pivot_wider</a></span><span class="op">(</span>names_from <span class="op">=</span> <span class="va">type</span>,
              values_from <span class="op">=</span> <span class="va">timestamp</span>,
              values_fn <span class="op">=</span> <span class="va">first</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">receive</span> <span class="op">&gt;</span> <span class="va">send</span><span class="op">)</span>

<span class="va">comms_pivot</span>
<span class="co">#&gt; # A tibble: 4,734 x 4</span>
<span class="co">#&gt;    station msg_code send                receive            </span>
<span class="co">#&gt;    &lt;chr&gt;      &lt;int&gt; &lt;dttm&gt;              &lt;dttm&gt;             </span>
<span class="co">#&gt;  1 D           2537 1999-01-21 03:37:57 1999-02-15 21:56:29</span>
<span class="co">#&gt;  2 C            720 1999-01-24 11:52:07 1999-02-22 12:24:57</span>
<span class="co">#&gt;  3 D           2531 1999-01-26 11:50:58 1999-02-09 07:14:33</span>
<span class="co">#&gt;  4 D           2992 1999-01-27 02:48:56 1999-02-22 12:05:55</span>
<span class="co">#&gt;  5 A           2262 1999-01-27 09:19:56 1999-02-11 19:43:42</span>
<span class="co">#&gt;  6 B           1785 1999-01-27 12:11:04 1999-02-07 03:07:50</span>
<span class="co">#&gt;  7 C           1624 1999-01-27 15:33:09 1999-02-20 05:07:54</span>
<span class="co">#&gt;  8 C           2280 1999-01-27 20:06:18 1999-02-18 11:25:13</span>
<span class="co">#&gt;  9 B           2137 1999-01-28 02:30:30 1999-02-26 17:13:21</span>
<span class="co">#&gt; 10 A            924 1999-01-28 18:41:03 1999-02-17 04:50:19</span>
<span class="co">#&gt; # … with 4,724 more rows</span></code></pre></div>
<p>Notice that pivot_wider produces 4734 rows compared to 24958 in <code>comms_conjecture</code>. What pairs are found in <code>comms_conjecture</code> that aren’t captured in <code>comms_pivot</code>?</p>
<p><strong>First</strong>, there a quite a few transmissions that do not elicit a response. conjecture doesn’t sweep these under the rug.</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">comms_pivot</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">receive</span><span class="op">)</span><span class="op">)</span>
<span class="co">#&gt; # A tibble: 0 x 4</span>
<span class="co">#&gt; # … with 4 variables: station &lt;chr&gt;, msg_code &lt;int&gt;, send &lt;dttm&gt;,</span>
<span class="co">#&gt; #   receive &lt;dttm&gt;</span>

<span class="va">comms_conjecture</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">receive</span><span class="op">)</span><span class="op">)</span>
<span class="co">#&gt; # A tibble: 10,857 x 4</span>
<span class="co">#&gt;    station msg_code send                receive            </span>
<span class="co">#&gt;    &lt;chr&gt;      &lt;int&gt; &lt;dttm&gt;              &lt;dttm&gt;             </span>
<span class="co">#&gt;  1 B           1170 1999-01-28 00:55:33 NA                 </span>
<span class="co">#&gt;  2 D           2258 1999-01-28 19:32:47 NA                 </span>
<span class="co">#&gt;  3 D           1519 1999-01-29 02:38:16 NA                 </span>
<span class="co">#&gt;  4 C           1799 1999-01-29 13:02:48 NA                 </span>
<span class="co">#&gt;  5 A            132 1999-01-29 18:21:29 NA                 </span>
<span class="co">#&gt;  6 C           1542 1999-01-30 04:57:17 NA                 </span>
<span class="co">#&gt;  7 B            791 1999-01-30 05:08:52 NA                 </span>
<span class="co">#&gt;  8 A           1548 1999-01-30 11:09:38 NA                 </span>
<span class="co">#&gt;  9 A            100 1999-01-30 15:55:40 NA                 </span>
<span class="co">#&gt; 10 C           2900 1999-01-30 20:18:50 NA                 </span>
<span class="co">#&gt; # … with 10,847 more rows</span></code></pre></div>
<p><strong>Second</strong>, our call to pivot_wider only returned the “first viable pairs” within each combination of <code>station</code> + <code>msg_code</code>. On the other hand, <code>comms_conjecture</code> contains 3 (4 including missing value) viable pairs for the below combination.</p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">comms_pivot</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">station</span> <span class="op">==</span> <span class="st">"A"</span>,
         <span class="va">msg_code</span> <span class="op">==</span> <span class="fl">221</span><span class="op">)</span>
<span class="co">#&gt; # A tibble: 1 x 4</span>
<span class="co">#&gt;   station msg_code send                receive            </span>
<span class="co">#&gt;   &lt;chr&gt;      &lt;int&gt; &lt;dttm&gt;              &lt;dttm&gt;             </span>
<span class="co">#&gt; 1 A            221 1999-02-05 16:52:22 1999-02-10 21:37:52</span>

<span class="va">comms_conjecture</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">station</span> <span class="op">==</span> <span class="st">"A"</span>,
         <span class="va">msg_code</span> <span class="op">==</span> <span class="fl">221</span><span class="op">)</span>
<span class="co">#&gt; # A tibble: 4 x 4</span>
<span class="co">#&gt;   station msg_code send                receive            </span>
<span class="co">#&gt;   &lt;chr&gt;      &lt;int&gt; &lt;dttm&gt;              &lt;dttm&gt;             </span>
<span class="co">#&gt; 1 A            221 1999-02-05 16:52:22 1999-02-10 21:37:52</span>
<span class="co">#&gt; 2 A            221 1999-02-11 15:38:03 1999-02-18 10:37:46</span>
<span class="co">#&gt; 3 A            221 1999-02-19 01:43:27 1999-02-21 12:29:59</span>
<span class="co">#&gt; 4 A            221 1999-03-01 07:26:50 NA</span></code></pre></div>
<p>The inclusion of multiple pairs for a given <code>station</code> + <code>msg_code</code> combination is the touchstone of conjecture.</p>
<div id="underlying-logic" class="section level3">
<h3 class="hasAnchor">
<a href="#underlying-logic" class="anchor"></a>Underlying Logic</h3>
<p>We’ll use a small fragment from <code>comms</code> to illustrate how conjecture works.</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">comms_small</span> <span class="op">&lt;-</span> <span class="va">comms</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">station</span> <span class="op">==</span> <span class="st">"A"</span>,
         <span class="va">msg_code</span> <span class="op">==</span> <span class="fl">221</span><span class="op">)</span>

<span class="va">comms_small</span>
<span class="co">#&gt; # A tibble: 7 x 4</span>
<span class="co">#&gt;   station timestamp           msg_code type   </span>
<span class="co">#&gt;   &lt;chr&gt;   &lt;dttm&gt;                 &lt;int&gt; &lt;chr&gt;  </span>
<span class="co">#&gt; 1 A       1999-02-05 16:52:22      221 send   </span>
<span class="co">#&gt; 2 A       1999-02-10 21:37:52      221 receive</span>
<span class="co">#&gt; 3 A       1999-02-11 15:38:03      221 send   </span>
<span class="co">#&gt; 4 A       1999-02-18 10:37:46      221 receive</span>
<span class="co">#&gt; 5 A       1999-02-19 01:43:27      221 send   </span>
<span class="co">#&gt; 6 A       1999-02-21 12:29:59      221 receive</span>
<span class="co">#&gt; 7 A       1999-03-01 07:26:50      221 send</span></code></pre></div>
<p>We can readily identify the send/receive pairs from the above observations. But how does conjecture accomplish this programmatically?</p>
<ol style="list-style-type: decimal">
<li>timestamps (specified by <code>sort_by = timestamps</code>) are separated into two vectors (specified by <code>names_from = type</code>).</li>
</ol>
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">send</span> <span class="op">&lt;-</span> <span class="va">comms_small</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">type</span> <span class="op">==</span> <span class="st">"send"</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">timestamp</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/base/sort.html">sort</a></span><span class="op">(</span><span class="op">)</span>
<span class="va">send</span>
<span class="co">#&gt; [1] "1999-02-05 16:52:22 CST" "1999-02-11 15:38:03 CST"</span>
<span class="co">#&gt; [3] "1999-02-19 01:43:27 CST" "1999-03-01 07:26:50 CST"</span>

<span class="va">receive</span> <span class="op">&lt;-</span> <span class="va">comms_small</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">type</span> <span class="op">==</span> <span class="st">"receive"</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">timestamp</span><span class="op">)</span> <span class="op">%&gt;%</span> <span class="fu"><a href="https://rdrr.io/r/base/sort.html">sort</a></span><span class="op">(</span><span class="op">)</span>
<span class="va">receive</span>
<span class="co">#&gt; [1] "1999-02-10 21:37:52 CST" "1999-02-18 10:37:46 CST"</span>
<span class="co">#&gt; [3] "1999-02-21 12:29:59 CST"</span></code></pre></div>
<ol start="2" style="list-style-type: decimal">
<li>Iterate through each element in <code>send</code>, with a nested loop for each element in <code>receive</code>. We can invert this hierarchy by setting <code>names_first = "receive"</code> instead.</li>
</ol>
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">output</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/integer.html">integer</a></span><span class="op">(</span>length <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">send</span><span class="op">)</span><span class="op">)</span>

<span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_along</a></span><span class="op">(</span><span class="va">send</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span>
  <span class="va">output</span><span class="op">[</span><span class="va">i</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="cn">NA_integer_</span>
  
  <span class="kw">for</span> <span class="op">(</span><span class="va">j</span> <span class="kw">in</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_along</a></span><span class="op">(</span><span class="va">receive</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span>
    <span class="kw">if</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">receive</span><span class="op">[</span><span class="va">j</span><span class="op">]</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span>
      <span class="kw">next</span>
    <span class="op">}</span> <span class="kw">else</span> <span class="kw">if</span> <span class="op">(</span><span class="va">receive</span><span class="op">[</span><span class="va">j</span><span class="op">]</span> <span class="op">&gt;</span> <span class="va">send</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">)</span> <span class="op">{</span>
      <span class="va">output</span><span class="op">[</span><span class="va">i</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="va">j</span>
      <span class="kw">break</span>
    <span class="op">}</span> <span class="kw">else</span> <span class="op">{</span>
      <span class="kw">next</span>
    <span class="op">}</span>
  <span class="op">}</span>
<span class="op">}</span>

<span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span><span class="va">send</span>, receive <span class="op">=</span> <span class="va">receive</span><span class="op">[</span><span class="va">output</span><span class="op">]</span><span class="op">)</span>
<span class="co">#&gt; # A tibble: 4 x 2</span>
<span class="co">#&gt;   send                receive            </span>
<span class="co">#&gt;   &lt;dttm&gt;              &lt;dttm&gt;             </span>
<span class="co">#&gt; 1 1999-02-05 16:52:22 1999-02-10 21:37:52</span>
<span class="co">#&gt; 2 1999-02-11 15:38:03 1999-02-18 10:37:46</span>
<span class="co">#&gt; 3 1999-02-19 01:43:27 1999-02-21 12:29:59</span>
<span class="co">#&gt; 4 1999-03-01 07:26:50 NA</span></code></pre></div>
<p>Conceptually, the above process flow is an accurate depiction of conjecture - though the underlying structure is more robust:</p>
<ul>
<li>conjecture reconciles the presence of additional columns, similar to conventional reshaping operations.</li>
<li>conjecture relies on C++ to execute the looping structure.</li>
</ul>
</div>
<div id="duplicate-posterior-values" class="section level3">
<h3 class="hasAnchor">
<a href="#duplicate-posterior-values" class="anchor"></a>Duplicate Posterior Values</h3>
<p>There is an important consequence associated with the above logic. We’ll demonstrate by removing all but <strong>one</strong> of the <code>receive</code> elements from <code>comms_small</code>.</p>
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># from comms small</span>
<span class="va">receive</span> <span class="op">&lt;-</span> <span class="va">receive</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span>

<span class="co"># rerun the algorithm</span>
<span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_along</a></span><span class="op">(</span><span class="va">send</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span>
  <span class="va">output</span><span class="op">[</span><span class="va">i</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="cn">NA_integer_</span>
  
  <span class="kw">for</span> <span class="op">(</span><span class="va">j</span> <span class="kw">in</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_along</a></span><span class="op">(</span><span class="va">receive</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span>
    <span class="kw">if</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">receive</span><span class="op">[</span><span class="va">j</span><span class="op">]</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span>
      <span class="kw">next</span>
    <span class="op">}</span> <span class="kw">else</span> <span class="kw">if</span> <span class="op">(</span><span class="va">receive</span><span class="op">[</span><span class="va">j</span><span class="op">]</span> <span class="op">&gt;</span> <span class="va">send</span><span class="op">[</span><span class="va">i</span><span class="op">]</span><span class="op">)</span> <span class="op">{</span>
      <span class="va">output</span><span class="op">[</span><span class="va">i</span><span class="op">]</span> <span class="op">&lt;-</span> <span class="va">j</span>
      <span class="kw">break</span>
    <span class="op">}</span> <span class="kw">else</span> <span class="op">{</span>
      <span class="kw">next</span>
    <span class="op">}</span>
  <span class="op">}</span>
<span class="op">}</span>

<span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span><span class="va">send</span>, receive <span class="op">=</span> <span class="va">receive</span><span class="op">[</span><span class="va">output</span><span class="op">]</span><span class="op">)</span>
<span class="co">#&gt; # A tibble: 4 x 2</span>
<span class="co">#&gt;   send                receive            </span>
<span class="co">#&gt;   &lt;dttm&gt;              &lt;dttm&gt;             </span>
<span class="co">#&gt; 1 1999-02-05 16:52:22 1999-02-21 12:29:59</span>
<span class="co">#&gt; 2 1999-02-11 15:38:03 1999-02-21 12:29:59</span>
<span class="co">#&gt; 3 1999-02-19 01:43:27 1999-02-21 12:29:59</span>
<span class="co">#&gt; 4 1999-03-01 07:26:50 NA</span></code></pre></div>
<p>Why does <code>1999-02-21 12:29:59</code> appear 3 times? Recall:</p>
<p>“for a given <code>send</code> transmission (anterior), the corresponding <code>receive</code> transmission (posterior) is the closest observation measured by <code>timestamp</code>.”</p>
<p>The above result is in accordance with this statement. However, at some point in the future, I may add the ability to drop repeat occurrences of posterior timestamps, which would produce the following result instead.</p>
<pre><code>#&gt; # A tibble: 4 x 2
#&gt;   send                receive            
#&gt;   &lt;dttm&gt;              &lt;dttm&gt;             
#&gt; 1 1999-02-05 16:52:22 1999-02-21 12:29:59
#&gt; 2 1999-02-11 15:38:03 NA                 
#&gt; 3 1999-02-19 01:43:27 NA                 
#&gt; 4 1999-03-01 07:26:50 NA</code></pre>
</div>
</div>
<div id="example-2-toll-lane-records" class="section level2">
<h2 class="hasAnchor">
<a href="#example-2-toll-lane-records" class="anchor"></a>Example 2: Toll Lane Records</h2>
<p>The <code>express</code> dataset contains toll records for <strong>northbound</strong> and <strong>southbound</strong> vehicles over the course of one business day.</p>
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://readr.tidyverse.org">readr</a></span><span class="op">)</span>

<span class="va">express</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv</a></span><span class="op">(</span><span class="st">"https://raw.githubusercontent.com/sccmckenzie/mopac/master/inst/extdata/express.csv"</span>, locale <span class="op">=</span> <span class="fu"><a href="https://readr.tidyverse.org/reference/locale.html">locale</a></span><span class="op">(</span>tz <span class="op">=</span> <span class="st">"US/Central"</span><span class="op">)</span><span class="op">)</span>

<span class="va">express</span>
<span class="co">#&gt; # A tibble: 13,032 x 6</span>
<span class="co">#&gt;    direction time                plate    make       model    color </span>
<span class="co">#&gt;    &lt;chr&gt;     &lt;dttm&gt;              &lt;chr&gt;    &lt;chr&gt;      &lt;chr&gt;    &lt;chr&gt; </span>
<span class="co">#&gt;  1 North     2020-05-20 05:00:33 DZR-4059 Mercedes   S-Series Black </span>
<span class="co">#&gt;  2 North     2020-05-20 05:01:13 GRG-4300 Nissan     Altima   Grey  </span>
<span class="co">#&gt;  3 North     2020-05-20 05:03:47 QZS-2886 Mazda      6        White </span>
<span class="co">#&gt;  4 North     2020-05-20 05:04:54 OHK-3972 BMW        i1       White </span>
<span class="co">#&gt;  5 North     2020-05-20 05:10:41 EAS-1671 Ford       F-250    Silver</span>
<span class="co">#&gt;  6 North     2020-05-20 05:13:53 OKP-7589 Dodge      Journey  White </span>
<span class="co">#&gt;  7 North     2020-05-20 05:13:55 HNN-1298 Volkswagen Passat   Grey  </span>
<span class="co">#&gt;  8 North     2020-05-20 05:15:59 EWL-6179 Toyota     Venza    Grey  </span>
<span class="co">#&gt;  9 North     2020-05-20 05:16:01 YVH-4374 GMC        Safari   White </span>
<span class="co">#&gt; 10 North     2020-05-20 05:18:16 DLU-6055 Nissan     Titan    Blue  </span>
<span class="co">#&gt; # … with 13,022 more rows</span></code></pre></div>
<p>Suppose we are interested in vehicles using the express lane both <code>North</code> and <code>South</code> (i.e. commuting to work). It’s up to us to designate an anterior <code>direction</code>. If we are only interested in vehicles commuting downtown, we set <code>names_first = "South"</code>.</p>
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/conjecture.html">conjecture</a></span><span class="op">(</span><span class="va">express</span>, <span class="va">time</span>, <span class="va">direction</span>, <span class="st">"South"</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/drop_na.html">drop_na</a></span><span class="op">(</span><span class="op">)</span> <span class="co"># We can't assume incomplete pairs are commuting to downtown</span>
<span class="co">#&gt; # A tibble: 1,069 x 6</span>
<span class="co">#&gt;    plate    make      model        color South               North              </span>
<span class="co">#&gt;    &lt;chr&gt;    &lt;chr&gt;     &lt;chr&gt;        &lt;chr&gt; &lt;dttm&gt;              &lt;dttm&gt;             </span>
<span class="co">#&gt;  1 QQA-8430 Nissan    370Z         Black 2020-05-20 05:00:16 2020-05-20 14:29:06</span>
<span class="co">#&gt;  2 NTL-6850 Ford      Crown Victo… Beige 2020-05-20 05:04:39 2020-05-20 18:09:47</span>
<span class="co">#&gt;  3 RBF-4890 Infiniti  QX60         Grey  2020-05-20 05:04:55 2020-05-20 16:32:07</span>
<span class="co">#&gt;  4 FDX-4994 Ford      Fusion       Grey  2020-05-20 05:12:38 2020-05-20 15:40:54</span>
<span class="co">#&gt;  5 DFF-5919 Honda     Accord       White 2020-05-20 05:14:32 2020-05-20 12:41:54</span>
<span class="co">#&gt;  6 CWW-1823 Porsche   Panamera     Black 2020-05-20 05:19:57 2020-05-20 16:15:45</span>
<span class="co">#&gt;  7 GRZ-3678 Volkswag… Eos          Red   2020-05-20 05:21:23 2020-05-20 17:53:49</span>
<span class="co">#&gt;  8 VMV-7990 Mercedes  GE-Class     Black 2020-05-20 05:23:14 2020-05-20 15:42:00</span>
<span class="co">#&gt;  9 YDR-9931 Mazda     3            White 2020-05-20 05:25:51 2020-05-20 14:46:11</span>
<span class="co">#&gt; 10 BWC-4843 Alfa Rom… Giulia       Red   2020-05-20 05:30:50 2020-05-20 16:34:49</span>
<span class="co">#&gt; # … with 1,059 more rows</span></code></pre></div>
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span>

<span class="fu"><a href="../reference/conjecture.html">conjecture</a></span><span class="op">(</span><span class="va">express</span>, <span class="va">time</span>, <span class="va">direction</span>, <span class="st">"South"</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/drop_na.html">drop_na</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>trip_length <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/difftime.html">difftime</a></span><span class="op">(</span><span class="va">North</span>, <span class="va">South</span>, units <span class="op">=</span> <span class="st">"hours"</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span> 
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">trip_length</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_histogram.html">geom_histogram</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<p><img src="conjecture_files/figure-html/unnamed-chunk-16-1.png" width="384"></p>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by <a href="http://sccm.io">Scott McKenzie</a>.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
